config/routes.rb
Rails.application.routes.draw do

    resources :labels, only: [:index, :show, :destroy]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

  namespace :api do
     namespace :v1 do
       resources :users, only: [:index, :show, :create, :update]
       resources :topics, except: [:edit, :new]
     end
   end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 1 }, presence: true
  validates :user, presence: true

  default_scope { order('updated_at DESC') }

  after_create :send_favorite_emails

   private

   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_many :labelings
  belongs_to :labelable, polymorphic: true
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
     new_labels = []

     unless label_string.nil? || label_string.empty?
       label_string.split(",").each do |label|
       label_name = label.strip
       new_label = Label.find_or_create_by(name: label_name)
       new_labels << new_label
       end
     end
     new_labels
   end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  # after_create :create_favorite

  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 1 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = (points*10) + age_in_days
    update_attribute(:rank, new_rank)
  end

  # def create_favorite
  #   Favorite.create(post: self, user: self.user)
  #   FavoriteMailer.new_post(self).deliver_now
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
  has_many :posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : where(public: true) }

  validates :name, length: { minimum: 1 }, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
    before_save { self.role ||= :member }

  before_create :generate_auth_token

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 100 },
            format: { with: EMAIL_REGEX }


  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
     favorites.where(post_id: post.id).first
  end

  def self.avatar_url(user, size)
     gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
     loop do
       self.auth_token = SecureRandom.base64(64)
       break unless User.find_by(auth_token: auth_token)
     end
   end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/models/vote_tid.rb
class VoteTid < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_to_update_posts?(post)
    current_user && (current_user == post.user || current_user.moderator? || current_user.admin?)
  end

  def user_is_authorized_to_destroy_posts?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_to_create_and_delete_topics?
    current_user && current_user.admin?
  end

  def user_is_authorized_to_edit_topics?
    current_user && (current_user.moderator? || current_user.admin?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_has_any_posts_or_comments?
    # current_user.posts > 0 || current_user.comments > 0
  end

# this is the helper method
  def render_posts_for(user)
    if user.posts.any?
      render(user.posts).html_safe
    else
      "<p>#{user.name} hasn't submitted any posts yet.</p>".html_safe
    end
  end

  def render_comments_for(user)
    if user.comments.any?
      render(user.comments).html_safe
    else
      "<p>#{user.name} hasn't submitted any comments yet.</p>".html_safe
    end
  end

  def render_favorite_posts_for(user)
    if user.favorites.any?
      render(user.favorites.map {|favorite| favorite.post}).html_safe
    else
      "<p>#{user.name} hasn't favorited any posts yet.</p>".html_safe
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<br>
<br>
<br>
<div class="text-center">
    <h3>SeoulTidbits is a crowd-sourced web application for the most</h3>
    <h2>compendious and useful insights to virtually anything in Seoul.</h2>
</div>
<br>
<br>
<br>
<div class="container-fluid bg-grey">
  <h2 class="text-center">CONTACT</h2>
  <div class="row">
    <div class="col-sm-5 pad-left">
      <p>We will respond within 1-2 business days.</p>
      <p><span class="glyphicon glyphicon-envelope"></span> admin@seoultidbits.com</p>
      <p><span class="glyphicon glyphicon-map-marker"></span> Seoul, South Korea</p>
    </div>
    <div class="col-sm-7">
      <div class="row">
        <div class="col-sm-6 form-group">
          <input class="form-control" id="name" name="name" placeholder="Name" type="text" required>
        </div>
        <div class="col-sm-6 form-group">
          <input class="form-control" id="email" name="email" placeholder="Email" type="email" required>
        </div>
      </div>
      <textarea class="form-control" id="comments" name="comments" placeholder="Comment" rows="5"></textarea><br>
      <div class="row">
        <div class="col-sm-12 form-group">
          <button class="btn btn-default pull-right" type="submit">Send</button>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<h5>A collaboration by Kyle Kwon and Stephen Hattersley</h5>
<h6>Special thanks to Christopher Beck</h6>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>FAQ</h1>

app/views/welcome/index.html.erb
<br>

<div class="jumbotron text-center">
  <h1>SeoulTidbits</h1>
  <p>SparkNotes for global travel.</p>
  <p>
    <% unless current_user %>
      <%= link_to "Sign In", new_session_path %> |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </p>
</div>

<div class="text-center">
  <h2>Featured Tidbits</h2>
</div>
<div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
    <h4>"Exit no. 9 is the most crowded entrance. Use Exit 2 instead."<br><span style="font-style:normal;">Hongik Station, Places</span></h4>
    </div>
    <div class="item">
      <h4>"The seats next to the doors to other cars are for elderly, pregnant, or injured people only."<br><span style="font-style:normal;">Seoul Subway, Living</span></h4>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<br>

<div class="container-fluid text-center">
  <h2>HOW IT WORKS</h2>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-list logo-small"></span>
      <h4>CATEGORIES</h4>
        <p>Culture</p>
        <p>Places</p>
        <p>Living</p>
        <p>Restaurants & Commerce</p>
        <br>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>TOPICS</h4>
        <p>Weddings</p>
        <p>Cafes</p>
        <p>Taxis</p>
        <p>Humbertos Mexican Restaurant</p>
        <br>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-comment logo-small"></span>
      <h4>TIDBITS</h4>
        <p>Concise</p>
        <p>Handy</p>
        <p>Up or down vote</p>
        <p>Highest voted at the top</p>
        <br>
    </div>
    </div>
    <br><br>
</div>

<footer class="container-fluid text-center">
  <a>
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a>
  <h5 class="footer-text">2016 SeoulTidbits</h5>
</footer>

<br>